### ISSUE TITLE
Noise on IMU messages

### ISSUE THREAD

**Issue by dow611** [BYU-MAGICC/ROSflight2#37]
@superjax @dpkoch 
After zooming in on the IMU data I realized that they are not evenly spaced in time as they should be. The first plot shows the raw data, while the second is a histogram of the inter-message time. The mean is 100Hz but no messages arrive at that rate. This issue is evident on all of the flight tests we have done at the REEF these last couple weeks.

![image](https://cloud.githubusercontent.com/assets/20246177/16528273/825813c8-3f81-11e6-808b-189dee061d03.png)

**Comment by superjax** [comment]
That is interesting to notice how they seem to come in groups of two.    What is the x-axis of the histogram?

**Comment by dow611** [comment]
Histogram of the inter-message time (seconds). We should see a spike at 0.01 only. The fact that there are 4 evenly spaced spikes is what's interesting to me.

**Comment by superjax** [comment]
Yeah... that's kinda odd.  I'll look into this if I have time later today.  I can just turn stuff on incrementally and see what is making the stream rate go like that.  Are the timestamps from arrival times or header stamp times.  (Dan just implemented some stuff that should adjust header stamp times to be accurate)  I can confirm that the measurements are actually taken at the correct intervals.

**Comment by superjax** [comment]
So, here is a sample which was run at 500 Hz using Dan's new timestamping
![imu_timing_test](https://cloud.githubusercontent.com/assets/7344014/16529401/ead607b8-3f7f-11e6-8523-e929ca60a581.jpg)

**Comment by dow611** [comment]
I was typing this:

It appears like both the inter-arrival times using header time stamps and rosbag meta times are both exhibit this behavior.

Dan just left for lunch, but he said that the most recent firmware (as of yesterday) may fix this issue?

**Comment by superjax** [comment]
Yeah, this is using today's firmware.

**Comment by dow611** [comment]
Well, this basically means that we have been running our rmekf at 50Hz so maybe we'll get better performance now?

**Comment by superjax** [comment]
Hopefully!  I don't know if Dan has told you, but we've set the default IMU stream rate to 500 Hz.  I still haven't seen any problems at 1000Hz, but to be safe, we dropped it to 500.

**Comment by dow611** [comment]
We flew with IMU at 500Hz. This picture is zoomed in a typical imu acc y (similar for acc x) Units are m/s/s vs. sec
![image](https://cloud.githubusercontent.com/assets/20246177/16627979/39ed261c-4375-11e6-8e6f-944f8b453fc8.png)

This is typical for gyros rad/s vs. sec
![image](https://cloud.githubusercontent.com/assets/20246177/16628039/76e922be-4375-11e6-96fd-76edd20363e5.png)


We don't know where that thick symmetric signal is coming from?! But it is saying we are bouncing back and forth between +/-5 m/s/s each dt!

The header inter-arrival times are pretty good
![image](https://cloud.githubusercontent.com/assets/20246177/16628290/c963f450-4376-11e6-9054-766c978fd2b3.png)

though ROS receives them in big clumps (metadata interarrival time is generally orders of magnitude faster)
![image](https://cloud.githubusercontent.com/assets/20246177/16628374/1e1b7a04-4377-11e6-8ed2-185c467d01df.png)



The estimates actually looked pretty good
Attitude (RPY in degrees vs time in sec)
![image](https://cloud.githubusercontent.com/assets/20246177/16628116/d66890f8-4375-11e6-9d94-c07a1c103b1a.png)

**Comment by superjax** [comment]
Well I'm glad that the estimates look good!  It's super weird that you're getting that flipping signal.  I'm going to set up a naze on shredder so I can fly it and see what is going on...  I bet it's a problem with how we are handling the data, rather than the raw data itself.  Perhaps I'm wrong though...

**Comment by superjax** [comment]
I assume you've balanced your props... haha

**Comment by dow611** [comment]
They have never even heard of prop balancing here. :) Could that be it?

**Comment by superjax** [comment]
Well, you'll only get better performance if you balance your props.  (the standard props that come with the 3DR quad kits are notorious for being out of balance - we generally use HQ props so we don't have to balance them),  Though that usually causes large amounts of noise in one axis, and tends to stay body-fixed.  I can't figure out why the noise would increase when you rolled.  I was making a joke more than anything.  I still think it's something that I've done wrong in the code.

**Comment by dow611** [comment]
My first impression is that is is some type of aliasing. When we use it in a low pass filter (RMEKF) the noisy data still works, so the 'noise' is clearly correlated. This phenomena doesn't show up at all when we are sitting on the ground or when moving the IMU without flying.  
Could also be something to do with our gel pad we mounted the IMU to?

**Comment by superjax** [comment]
Maybe... Do you have another IMU onboard that you can read, or are you flying the PixHawk?  I'm trying to see if I can see this behavior on our Microstrain, but it doesn't stream as fast, so It's a little hard to compare apples to apples.

**Comment by superjax** [comment]
Here's a video on how to balance props [video](https://www.youtube.com/watch?v=4_fL_QuMkp8)

**Comment by dow611** [comment]
Perhaps you fly shredder as is, but throw a Naze on as an external IMU and record?

**Comment by superjax** [comment]
That's the plan.  I'm getting that ready as we speak

**Comment by dpkoch** [comment]
For comparison, here's 4 seconds of data from the x-axis accelerometer on the Pixhawk:
![image](https://cloud.githubusercontent.com/assets/2702490/16632317/2f0fcb50-4389-11e6-836c-d53aa5fcc7c1.png)

The pattern does still seems to be there, but it's less well-defined and of significantly lower magnitude.

**Comment by superjax** [comment]
![image](https://cloud.githubusercontent.com/assets/7344014/16633145/10dffdde-4385-11e6-94e8-556c8dcc84ce.png)
Here is the plot of the naze vs microstrain.  I also put in a filtered version of the naze (4-part moving average).  I think that is likely why the data on the naze is so noisy.  It is completely unfiltered.

**Comment by superjax** [comment]
Here is zoomed on on 4 seconds
![image](https://cloud.githubusercontent.com/assets/7344014/16633364/2fb2d7c6-4386-11e6-8c16-4ef0fe0ce2ca.png)

Here is the filtered version for 4 seconds
![image](https://cloud.githubusercontent.com/assets/7344014/16633399/67973d4e-4386-11e6-8c49-b1eb005ce5a4.png)

**Comment by superjax** [comment]
So, I'm working on getting the DMP running, to see what it looks like.  I don't really know what to do about this.  What do you think @dpkoch @dow611?

**Comment by dow611** [comment]
dock_figure('Aliasing',10);
    t = 0:0.001:1000;
    y = sin(t);
    mask = 1:3100:length(t);
    tt = t(mask);
    yy = y(mask);
    plot(t,y); hold on;
    plot(tt,yy,'rx-')
    axis([0 1000 -2 2 ])`

![image](https://cloud.githubusercontent.com/assets/20246177/16639635/f4fd9ec8-43b6-11e6-8186-f60c0d8a5c5a.png)

Look familiar? Kevin suggested that it could be a high frequency oscillation (blue) that when we sample at 0.002 it creates our lobes. 

Since we already have a filter, we could 'filter' the data in the rmekf (like we just did) or we could do a moving average. The moving average would result in much smaller variance and a much more reaslistic value at any given time. The later makes sense to me. The measurements would become strongly correlated if we do a moving average and keep it at 500Hz so perhaps it would be best to publish the average of every 5 measurements (no overlap)? Thoughts?

**Comment by superjax** [comment]
We can also set the LPF on the accelerometer itself.

![image](https://cloud.githubusercontent.com/assets/7344014/16643846/8536fe9e-43d5-11e6-9224-a970ff6e286a.png)

Before I left work today, I set up the DMP to work within ROSflight.  After letting it simmer on the backburner this evening, I realized that perhaps I could pretty easily throw some soft rubber under the Naze and hopefully filter some of that high-frequency stuff out.  Looking at that graph above, it makes a lot of sense.

Tomorrow morning, I'll try running the DMP (limits us to 200Hz, but lots of data processing comes for free), then I'll try adding rubber, flying first it with the raw values, then again after changing the DLPF in the MPU.

**Comment by dpkoch** [comment]
@dow611 That plot is very interesting; it looks very similar to what we're seeing. To me that makes prop vibrations seem like a pretty likely suspect; hopefully balancing the props will help. It's also possible that the green gel goo we have our naze mounted on is too stiff, or that the structure it's mounted on that also has a big computer strapped to it is contributing to the vibrations.

@superjax Yeah I think it'd be interesting to see what a light LPF does to the data. The DMP would be interesting to see, but long-term I think it's a no-go due to licensing issues. As far as filtering with the DLPF vs. a windowed average on the Naze, I'd say let's make the MPU6050 do the work if it gives us the performance we need?

**Comment by superjax** [comment]
Here are some other ideas for vibration damping. [Link](http://ardupilot.org/copter/docs/common-vibration-damping.html)

**Comment by superjax** [comment]
Okay, here are the results of my first investigation:

The DMP didn't do anything to help.  It looks like the DMP doesn't do any additional filtering beyond the built-in LPF register.

I did a little test with each of the LPF settings.  I set shredder on the cart, and armed the Pixhawk so the motors would spin. I didn't fly it, but I just wanted to see what the noise would be with the motors armed, because if it was too noisy just sitting there, then flying would definitely be bad.

![img_20160707_135105](https://cloud.githubusercontent.com/assets/7344014/16667690/0bd83d1c-444b-11e6-9d32-afcd6f2ca10b.jpg)

So here are the results of each test.  Starting with the LPF off:
![lpf_off](https://cloud.githubusercontent.com/assets/7344014/16667707/1c9f93e8-444b-11e6-93ed-5d65d69aa074.png)
Then at 256 Hz
![lpf_256hz](https://cloud.githubusercontent.com/assets/7344014/16667710/21b7b5cc-444b-11e6-8add-a14d13621a26.png)
Then 188 Hz
![lpf_188hz](https://cloud.githubusercontent.com/assets/7344014/16667713/272aaffa-444b-11e6-984c-32df7df99e57.png)
Then 98 Hz
![lpf_98hz](https://cloud.githubusercontent.com/assets/7344014/16667721/2c10c112-444b-11e6-9015-3a2fdd94b7d4.png)
42 Hz
![lpf_42hz](https://cloud.githubusercontent.com/assets/7344014/16667730/327ca8d6-444b-11e6-9d3e-5cd219edd85f.png)
20 Hz
![lpf_20hz](https://cloud.githubusercontent.com/assets/7344014/16667735/379ea198-444b-11e6-878e-4056f457c462.png)
10 Hz
![lpf_10hz](https://cloud.githubusercontent.com/assets/7344014/16667740/3cb7aeea-444b-11e6-99a0-f0166906a314.png)
and 5 Hz
![lpf_5hz](https://cloud.githubusercontent.com/assets/7344014/16667745/402c6b2e-444b-11e6-84e4-0d357ffe0011.png)

These are all plotted on the same scale (using the PyQtGraph engine in `rqt_plot` so it actually displays all the data - as opposed to the Matplotlib engine)

I think what I need to do next is fly some of the lower filter values.  I'm afraid that 5 Hz and 10Hz might be a little slow, but 20  or 42 might do the trick.  I did some digging, cleanflight uses 188Hz, while some power-users use 256 Hz, but those quads are generally way smaller than shredder or the 3DR quads, have smaller propellers (which cause less vibration), and faster dynamics.  I think that for shredder we'll probably want to drop down.  Especially with the results I just got.

**Comment by dpkoch** [comment]
Cool deal. My only concern with filtering as aggressive as 20 or 42Hz is the delay (5 and 8 ms respectively). That seems like it's starting to get significant. Do you think 98Hz (3ms delay) would give us enough?

**Comment by superjax** [comment]
Perhaps!  I haven't had time to test it yet, but after I eat real quick, I do a few flight tests and post the results.  I'll also try to record all the information we would need to run two estimators in parallel, one with the microstrain IMU and one with the Naze.  It might be interesting to see how the LPF affects performance once it goes through the RMEKF, because as David pointed out, this noise will not agree with the dynamics at all, so it will likely get filtered out.

**Comment by dow611** [comment]
Thoughts:
- First, this seems like a great Dr McLain question. @superjax do you mind asking?
- If we know the delay and it's fairly constant (likely) then we can subtract it from the timestamp and the RMEKF will deal with it accordingly.
- The RMEKF is a low pass filter. Since we integrate the IMU in our dynamics, spikes high and low likely have limited negative consequences. Say we apply 10m/s/s on Ax for 0.002s and then -9.9m/s/s for 0.002s, etc. Overall, the vehicle is never allowed to 'take off' and in practice (given the one run we did as an example) it is as if the filter received the appropriate input (more or less). The crazy measurements are weighted by their dt in the filter.
- We might want to run a few more flight tests, but I leaning towards keeping it faster (freshest data is available) and forcing the RMEKF to deal with some of the noise. But I dunno?

**Comment by superjax** [comment]
Okay, here are the results of my test.  I flew Shredder with the naze and the microstrain IMU at the same time, but varying the naze's LPF.


![20hz](https://cloud.githubusercontent.com/assets/7344014/16672311/948b2400-4462-11e6-9288-5ec5fd3723a2.png)
![42hz](https://cloud.githubusercontent.com/assets/7344014/16672313/9706e598-4462-11e6-9743-e960764436c4.png)
![98hz](https://cloud.githubusercontent.com/assets/7344014/16672314/985cd7f4-4462-11e6-97b5-a5bf492daa61.png)
![188hz](https://cloud.githubusercontent.com/assets/7344014/16672316/9aaf8e0c-4462-11e6-9b7c-d54ff43bc4be.png)

I don't really know what to make of it.  I have the bags though, so we could run it through RMEKF to see how performance changes
[naze_bags.zip](https://github.com/BYU-MAGICC/ROSflight2/files/353203/naze_bags.zip)

**Comment by superjax** [comment]
Also, Dr. McLain is out of town.  He will be back on Monday, and I will definitely ask him.  It's very much up his alley.

**Comment by superjax** [comment]
Spoke with Dr. McLain:

He thinks that we should look into better mechanical filtering (mounting it better) before performing any digital filtering.  He pointed out that the Kalman filter is a low-pass filter of a sort, but doesn't introduce delay like the LPF on the MPU6050, so it should probably perform pretty well even with high-frequency noise on the data.

He said to start, I should try to mount the naze right on the microstrain.  That way we are comparing apples to apples, but that it's probably not the sensor, because the naze isn't "making up" noise, it's just seeing more noise, and is capable of sending more of it, simply because it is read faster, and has worse mechanical filtering.

I sum, he didn't seem terribly concerned.  He sort of felt that if the estimates were good, then there wasn't much to worry about, and we could probably do a better job of mounting the naze and get better data.  He didn't think it was a good idea to do heavy LPF onboard the MPU6050, because the Kalman Filter would do a better job.

**Comment by superjax** [comment]
Dr. McLain sent me this paper about this issue
[20160712_095217.pdf](https://github.com/BYU-MAGICC/ROSflight2/files/360213/20160712_095217.pdf)
